# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gaia < Formula
  desc "Cli tool to ask local LLM with ollama"
  homepage "https://github.com/vonglasow/gaia"
  version "2.7.1"
  license "GPL3"

  on_macos do
    on_intel do
      url "https://github.com/vonglasow/gaia/releases/download/v2.7.1/gaia_2.7.1_darwin_amd64.tar.gz"
      sha256 "6106cf17e859791302f1cf65e63e727516a8c1cce93d07d6a167df5ec2e814b8"

      def install
        bin.install "gaia"
      end
    end
    on_arm do
      url "https://github.com/vonglasow/gaia/releases/download/v2.7.1/gaia_2.7.1_darwin_arm64.tar.gz"
      sha256 "7f071e59391e79936e309aea8b4f83906955074f6a7b72a8a5ec501a046d7924"

      def install
        bin.install "gaia"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vonglasow/gaia/releases/download/v2.7.1/gaia_2.7.1_linux_amd64.tar.gz"
        sha256 "c5d43915f6217af03eb875256d6b4555fe285c33248c82e4db185cacdf487148"

        def install
          bin.install "gaia"
        end
      end
    end
  end
end
