# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GaiaAT215 < Formula
  desc "CLI to interact with local/remote LLMs (Ollama, OpenAI, Mistral), run tool actions and operator (investigate) mode"
  homepage "https://github.com/vonglasow/gaia"
  version "2.15.0"
  license "GPL3"

  on_macos do
    on_intel do
      url "https://github.com/vonglasow/gaia/releases/download/v2.15.0/gaia_2.15.0_darwin_amd64.tar.gz"
      sha256 "34e8749a9ce049909980a0279bb89c3344cd2e1ec77f7a1e404f754546d840fd"

      def install
        bin.install "gaia"
      end
    end
    on_arm do
      url "https://github.com/vonglasow/gaia/releases/download/v2.15.0/gaia_2.15.0_darwin_arm64.tar.gz"
      sha256 "4943a87a01d0a670b0799de61b9e70e3807988748cf4997a7f79c2719dbba9ab"

      def install
        bin.install "gaia"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vonglasow/gaia/releases/download/v2.15.0/gaia_2.15.0_linux_amd64.tar.gz"
        sha256 "0cd312c1d57d68ba0fb8ee8cbe69f9b07569b1d6ad1a152658608e76c8f5d738"

        def install
          bin.install "gaia"
        end
      end
    end
  end
end
