# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gaia < Formula
  desc "CLI to interact with local/remote LLMs (Ollama, OpenAI, Mistral), run tool actions and operator (investigate) mode"
  homepage "https://github.com/vonglasow/gaia"
  version "3.0.0"
  license "GPL3"

  on_macos do
    on_intel do
      url "https://github.com/vonglasow/gaia/releases/download/v3.0.0/gaia_3.0.0_darwin_amd64.tar.gz"
      sha256 "ee10acf2f4c958895e14617e871923b62c797eb2f43e8e0b64e1818c539a4be9"

      def install
        bin.install "gaia"
      end
    end
    on_arm do
      url "https://github.com/vonglasow/gaia/releases/download/v3.0.0/gaia_3.0.0_darwin_arm64.tar.gz"
      sha256 "68e0ff55c22e7101eac5a28b05d2d0b9ea6faebf7c9721e05319dc3a0b3d1ab7"

      def install
        bin.install "gaia"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vonglasow/gaia/releases/download/v3.0.0/gaia_3.0.0_linux_amd64.tar.gz"
        sha256 "35c3ef30ff3fa2321c134f944a8dafdd0c2ad36bff200d237b0e0d6101ce1d9e"

        def install
          bin.install "gaia"
        end
      end
    end
  end
end
