# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GaiaAT26 < Formula
  desc "Cli tool to ask local LLM with ollama"
  homepage "https://github.com/vonglasow/gaia"
  version "2.6.5"
  license "GPL3"

  on_macos do
    on_intel do
      url "https://github.com/vonglasow/gaia/releases/download/v2.6.5/gaia_2.6.5_darwin_amd64.tar.gz"
      sha256 "d2a4e7a46aa9d280fa4c543fc19cd74fa5281e4c7ac5098ef3eaaa3412fc4761"

      def install
        bin.install "gaia"
      end
    end
    on_arm do
      url "https://github.com/vonglasow/gaia/releases/download/v2.6.5/gaia_2.6.5_darwin_arm64.tar.gz"
      sha256 "a42586da73b2a8f2426472f9617b55ce9981f4d49d46d078d895ea38d79bca7c"

      def install
        bin.install "gaia"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vonglasow/gaia/releases/download/v2.6.5/gaia_2.6.5_linux_amd64.tar.gz"
        sha256 "41fad2d67ba866dfc3b9e910699bc0904603bc2a1850a63d85041126fcdaedb0"

        def install
          bin.install "gaia"
        end
      end
    end
  end
end
