# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GaiaAT29 < Formula
  desc "Cli tool to ask local LLM with ollama"
  homepage "https://github.com/vonglasow/gaia"
  version "2.9.0"
  license "GPL3"

  on_macos do
    on_intel do
      url "https://github.com/vonglasow/gaia/releases/download/v2.9.0/gaia_2.9.0_darwin_amd64.tar.gz"
      sha256 "c1c0b55aa2790eba78a4434fcdaa311106bcfff99032924a8a8b008ff4b35f1b"

      def install
        bin.install "gaia"
      end
    end
    on_arm do
      url "https://github.com/vonglasow/gaia/releases/download/v2.9.0/gaia_2.9.0_darwin_arm64.tar.gz"
      sha256 "82b3860cb0f7c04c5167113e3b25f262ee614d633f59cd115d3301cbafebec0c"

      def install
        bin.install "gaia"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vonglasow/gaia/releases/download/v2.9.0/gaia_2.9.0_linux_amd64.tar.gz"
        sha256 "43eda5e3b04c63d2e7ff31c592971cb5eb717842eceacd4d0faf61853b21f2b1"

        def install
          bin.install "gaia"
        end
      end
    end
  end
end
