# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GaiaAT213 < Formula
  desc "CLI to interact with local/remote LLMs (Ollama, OpenAI, Mistral), run tool actions and operator (investigate) mode"
  homepage "https://github.com/vonglasow/gaia"
  version "2.13.0"
  license "GPL3"

  on_macos do
    on_intel do
      url "https://github.com/vonglasow/gaia/releases/download/v2.13.0/gaia_2.13.0_darwin_amd64.tar.gz"
      sha256 "4aa2c5651d60e864cf952efe9c1a805ec077655d47af65911af7640bf4c8a94d"

      def install
        bin.install "gaia"
      end
    end
    on_arm do
      url "https://github.com/vonglasow/gaia/releases/download/v2.13.0/gaia_2.13.0_darwin_arm64.tar.gz"
      sha256 "63eda3236078968fb4bdc7ead94808bad1dac596301c7621b819a6572266dfa2"

      def install
        bin.install "gaia"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vonglasow/gaia/releases/download/v2.13.0/gaia_2.13.0_linux_amd64.tar.gz"
        sha256 "3892e061c06c95f36117582133769ead3b9f6110f99b977855876fac9980388a"

        def install
          bin.install "gaia"
        end
      end
    end
  end
end
