# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GaiaAT210 < Formula
  desc "Cli tool to ask local LLM with ollama"
  homepage "https://github.com/vonglasow/gaia"
  version "2.10.0"
  license "GPL3"

  on_macos do
    on_intel do
      url "https://github.com/vonglasow/gaia/releases/download/v2.10.0/gaia_2.10.0_darwin_amd64.tar.gz"
      sha256 "24e50a4588fdd1e56b895ef9cc3f26c01182ba36dc5c9689b09883513e19ba90"

      def install
        bin.install "gaia"
      end
    end
    on_arm do
      url "https://github.com/vonglasow/gaia/releases/download/v2.10.0/gaia_2.10.0_darwin_arm64.tar.gz"
      sha256 "1116f3a3eafdd11c96c9ea5401a96bbf6ca82ef812cb109eff755940e2c7f55d"

      def install
        bin.install "gaia"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vonglasow/gaia/releases/download/v2.10.0/gaia_2.10.0_linux_amd64.tar.gz"
        sha256 "3525d2f436327f2bd6264beb1c33dba21e3cf70fd92817d5f856d0b830e6bc06"

        def install
          bin.install "gaia"
        end
      end
    end
  end
end
